app:
  url: http://localhost:8080

upload:
  dir: ./images

server:
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gadgetzone?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: jdbc

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: demavarlamov@gmail.com
    password: "lnio eszi aeyy sztd"
    protocol: smtp
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          from: demavarlamov@gmail.com
        debug: true

logging:
  level:
    "[org.springframework.jdbc.core]": DEBUG
    "[org.springframework.jdbc.resultset]": TRACE
    "[com.GadgetZone.dao]": DEBUG
    "[org.springframework.mail]": DEBUG
    "[com.GadgetZone]": DEBUG
    org.springframework.security.authentication: DEBUG
    com.GadgetZone.service.CustomUserDetailsService: TRACE
