spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gadget_zone?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-on-migrate: true