spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gadgetzone?useSSL=false&serverTimezone=UTC
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true 
    locations: classpath:db/migration 